### PR TITLE
enhanced readme fixed : #8

### PR DESCRIPTION
**Pull request by rudransh61**
Done !!
Readme completed !!!!

### CODE REVIEW

**Comment by rudransh61** [comment]
What is SWOC , id care merge this

**Comment by rudransh61** [comment]
Oooooo misclicked something

**Comment by rudransh61** [comment]
Sory i misclicked to sync repo , i will again make a pr tomorrow

**Comment by rudransh61** [comment]
And i dont know what is this swoc

**Comment by pinak22dhir** [comment]
ok @rudransh61 make issue first i will assigned you , make a pr

**Pull request closed without merging**
